# Generated by Django 6.0.4 on 2026-04-19 22:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Укажи процент скидки вручную для отображения итоговой суммы в админке (например 10.00)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
