# Generated by Django 6.0.4 on 2026-04-21 04:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discount_percent_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional percent value used to display discounted order total in Django admin', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
